/**
 * Photography used by the marketing sections, as opposed to the product
 * catalogue in `content/tables/tables.ts`.
 *
 * GENERATED by `scripts/import-section-images.mjs` from the `sections images/`
 * folder in the workspace root. Rerun that script rather than editing this file.
 *
 * Each entry carries its intrinsic size and a 16px inline blur placeholder, so a
 * section can render a fixed-ratio frame that paints in the photograph's own
 * colours before the full file arrives. Alt text is NOT here — it lives in
 * `messages/*.json` so it can be translated.
 */

export type SectionImage = {
  src: string;
  width: number;
  height: number;
  /** ~150 byte inline WebP for first paint. */
  blurDataURL: string;
};

/** Home hero: Walnut live-edge coffee table with a turquoise resin river, styled with books and a plant in a bright living room */
export const heroImage: SectionImage = {
  src: '/images/hero-walnut-turquoise-resin-river-coffee-table.webp',
  width: 1254,
  height: 1254,
  blurDataURL:
    'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoQABAAAwBSJYgCdACktKyAAP7ER19zDRLkG405bnNlE/kOgZhdp/kcSYGF9+cWOL9dOF64xW8gAA==',
};

/** Inquiry CTA: Live-edge walnut coffee table set into a brushed steel surround, beside a dark leather sofa */
export const ctaImage: SectionImage = {
  src: '/images/cta-live-edge-walnut-steel-coffee-table.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAgCdASoQAAsAAwBSJQBOgBn7iySyKfcAAP7xpIiakdOXV9pnzUS4tSq+mL9goeVFAy5NoAA=',
};

/** Our Craft — lead image: Finished walnut table with a vivid blue resin river, on trestles in the workshop, seen from above */
export const craftLeadImage: SectionImage = {
  src: '/images/our-craft-blue-resin-river-table-workshop.webp',
  width: 1068,
  height: 1472,
  blurDataURL:
    'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABYAPt1cp0yopSOiMAgBEBuJQBOgBCuidfiiGJAASgFgAP7MKMkYPsOL5O6Ef2TQveKm9YI8K9e/vumizSoaz2tF30OeSv5T7GHKBj+4aR49D4fRHJiXqKrJwHsAAAA=',
};

/** Our Craft — cinematic break: Green epoxy resin being poured from a bucket into a mould around a walnut slab */
export const craftPourImage: SectionImage = {
  src: '/images/our-craft-green-resin-pour-in-progress.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAsAAwBSJZACdADRByRLKAD+2FKq0PKSPIMMmXfueF5afl2ob6TRO6Zyh9KAdC8PFonpf6hMucFyAAA=',
};

/** Contact page: Round walnut coffee table with a dark resin river on a black steel base, standing on a workbench in the workshop with slabs racked behind it */
export const contactImage: SectionImage = {
  src: '/images/contact-round-walnut-resin-table-in-workshop.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQAAsAAwBSJQBOgBu1IXMySAAA/oP2cKTx0HnBjlId+E9V9/EOauHM1BoySEHILvwAAA==',
};

/** Inquiry success: Walnut dining table with an emerald resin river in a client dining room, six cream chairs around it and a pool through the glass doors */
export const enquiryReceivedImage: SectionImage = {
  src: '/images/enquiry-received-walnut-emerald-resin-dining-table.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAsAAwBSJZgCdADPvNoLgAD+gUrjiF+i90s8PtkVKBuGpJJ1X1gdF8+siEHesnfqsmAA',
};

/** Our Craft — phase 1 (Consultation): Finished walnut dining table with a black resin river, six cream chairs around it in a client dining room */
export const craftPhase1Image: SectionImage = {
  src: '/images/craft-phase-1-walnut-black-resin-dining-table-client-home.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAgCdASoQAAsAAwBSJaACdAEKuo6yR5MAAP7Xk1xRGMdRGLdsagzptocYMjXLC15b6GHYAAA=',
};

/** Our Craft — phase 2 (Design): Completed walnut table with a black resin river and a sculpted timber base, photographed head-on in the workshop */
export const craftPhase2Image: SectionImage = {
  src: '/images/craft-phase-2-finished-walnut-resin-table-in-workshop.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAAsAAwBSJZACdADbqx5S4AAA/uTjTYq60c1kwS1B2tjFbQoJKVc0MQJjk511WKU7dgAA',
};

/** Our Craft — phase 3 (Selection): Craftsman guiding a rough walnut slab with its bark edge intact through a workshop bandsaw */
export const craftPhase3Image: SectionImage = {
  src: '/images/craft-phase-3-walnut-slab-milled-on-bandsaw.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAQCdASoQAAsAAwBSJQBOgBHquAAA/duaYfnlTF0UtM+6epPuBi6joAb67/ExpgHjOYQAAAA=',
};

/** Our Craft — phase 4 (Production): Craftsman trimming the edge of a cured walnut and resin table top with a circular saw against a straight guide */
export const craftPhase4Image: SectionImage = {
  src: '/images/craft-phase-4-trimming-cured-resin-table-top.webp',
  width: 1672,
  height: 941,
  blurDataURL:
    'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoQAAkAAwBSJYgCdAEfPETCjwAA/vWh2aOdYDlvQdXBxBjHlztvWO7TLYRwnAAA',
};

/** Our Craft — phase 5 (Delivery): Two Benzart Resin staff in branded coats carrying a wrapped table through the doorway of a client villa */
export const craftPhase5Image: SectionImage = {
  src: '/images/craft-phase-5-wrapped-table-delivered-to-villa.webp',
  width: 1536,
  height: 1024,
  blurDataURL:
    'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAsAAwBSJaACdACv4xQ4AAD88WYXzRH62rcmeWflNQ9iyGmXEedV51VwfmB/+ZNSztt+XxlldcAA',
};

/**
 * The five commissioning phases, in the order they appear on Our Craft.
 *
 * Exported as an array because `OurCraftClient` renders `OurCraft.phases` from
 * the message files and needs to pair each authored step with its photograph by
 * index. Previously the component held a local array of five `/images/*.png`
 * paths, three of which duplicated images used elsewhere on the same page.
 */
export const craftPhaseImages: SectionImage[] = [
  craftPhase1Image,
  craftPhase2Image,
  craftPhase3Image,
  craftPhase4Image,
  craftPhase5Image,
];
